---
- name: initial setup - hostname - base packages
  hosts: all
  become: yes
  become_user: root
  tasks:
#    - name: "set hostname"
#      hostname: name={{ inventory_hostname }}
  roles:
    - base
