---
- name: restart_machine
  shell: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting_come_back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60
  become: false
