---
- name: copy kubernetes binaries
  copy: src={{item}} dest=/usr/bin/{{item}} mode=0755
  with_items:
    - kubelet
    - kubectl

- name: Create Kubernetes config directory
  file: path=/etc/kubernetes/manifests/ state=directory recurse=yes owner=root group=root mode=0755

- name: Copy configuration
  template: src={{ mode }}/kubernetes.yml.j2 dest=/etc/kubernetes/manifests/kubernetes.yaml

- name: Setup profile
  template: src=kubernetes_profile.sh.j2 dest=/etc/profile.d/kubernetes.sh mode=0644

- name: Install kubelet service definition
  template: src=kubelet.service.j2 dest=/lib/systemd/system/kubelet.service owner=root group=root mode=0644
  register: result

- name: Reload systemd when service definition changed
  command: systemctl daemon-reload
  when: result|changed

- name: Restart kubelet
  service: name=kubelet enabled=yes state=restarted
