---
- name: set hostname
  hostname: name={{ inventory_hostname }}

- name: expand paritions if needed
  include: partitions.yml

- name: add and update packages
  include: apt.yml

- name: setup ssh keys
  include: user.yml

- name: Add Swapfile
  include: swap.yml

- name: Setup system parameters (boot, hosts, timzone)
  include: system.yml
